version: '2'

networks:
  app-network:
    driver: bridge

services:
  web:
    image: 'nodebackend'
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    networks:
      - app-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
